server:
  port: 8080

spring:
  application:
      name: brokage-firm-challange

  datasource:
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username: root
    password: pass

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  security:
    user:
      name: admin
      password: pass

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
